# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whvRKupg5FPssVZ5u_levsTLHxvdB8rO
"""

!pip install flask flask-ngrok

from flask import Flask, request, jsonify
from flask_ngrok import run_with_ngrok
import sqlite3
import secrets
from datetime import datetime

app = Flask(__name__)
run_with_ngrok(app)  # For testing in Colab

# DB setup (create if not exists)
def init_db():
    conn = sqlite3.connect("database.db")
    cur = conn.cursor()
    cur.execute('''CREATE TABLE IF NOT EXISTS urls (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        url TEXT NOT NULL,
        shortCode TEXT UNIQUE NOT NULL,
        createdAt TEXT NOT NULL,
        updatedAt TEXT NOT NULL,
        accessCount INTEGER DEFAULT 0
    )''')
    conn.commit()
    conn.close()

init_db()

@app.route('/shorten', methods=['POST'])
def create_short_url():
    data = request.get_json()
    url = data.get('url')

    if not url:
        return jsonify({"error": "URL is required"}), 400

    short_code = secrets.token_urlsafe(4)[:6]
    now = datetime.utcnow().isoformat()

    conn = sqlite3.connect("database.db")
    cur = conn.cursor()
    cur.execute("INSERT INTO urls (url, shortCode, createdAt, updatedAt) VALUES (?, ?, ?, ?)",
                (url, short_code, now, now))
    conn.commit()
    new_id = cur.lastrowid
    conn.close()

    return jsonify({
        "id": new_id,
        "url": url,
        "shortCode": short_code,
        "createdAt": now,
        "updatedAt": now
    }), 201

