# -*- coding: utf-8 -*-
"""utility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5dYO4JYKzcSXG6HHIFCVeprkziknn6a
"""

import sqlite3
import secrets
from datetime import datetime

def init_db():
    conn = sqlite3.connect("database.db")
    cur = conn.cursor()
    cur.execute('''CREATE TABLE IF NOT EXISTS urls (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        url TEXT NOT NULL,
        shortCode TEXT UNIQUE NOT NULL,
        createdAt TEXT NOT NULL,
        updatedAt TEXT NOT NULL,
        accessCount INTEGER DEFAULT 0
    )''')
    conn.commit()
    conn.close()

init_db()


def create_short_url(url):
    short_code = secrets.token_urlsafe(4)[:6]
    now = datetime.utcnow().isoformat()

    conn = sqlite3.connect("database.db")
    cur = conn.cursor()
    cur.execute("INSERT INTO urls (url, shortCode, createdAt, updatedAt) VALUES (?, ?, ?, ?)",
                (url, short_code, now, now))
    conn.commit()
    new_id = cur.lastrowid
    conn.close()

    return {
        "id": new_id,
        "url": url,
        "shortCode": short_code,
        "createdAt": now,
        "updatedAt": now
    }

# 🔸 Test it:
create_short_url("https://www.example.com/long/url")


def get_original_url(short_code):
    conn = sqlite3.connect("database.db")
    cur = conn.cursor()

    cur.execute("SELECT id, url, shortCode, createdAt, updatedAt, accessCount FROM urls WHERE shortCode = ?", (short_code,))
    row = cur.fetchone()

    if row:
        # Update access count
        cur.execute("UPDATE urls SET accessCount = accessCount + 1 WHERE shortCode = ?", (short_code,))
        conn.commit()
        conn.close()

        return {
            "id": row[0],
            "url": row[1],
            "shortCode": row[2],
            "createdAt": row[3],
            "updatedAt": row[4],
            "accessCount": row[5] + 1  # incremented
        }
    else:
        conn.close()
        return {"error": "Short code not found"}

# 🔸 Test it:
get_original_url("abc123")  # Replace with real code you got


def update_url(short_code, new_url):
    now = datetime.utcnow().isoformat()
    conn = sqlite3.connect("database.db")
    cur = conn.cursor()
    cur.execute("UPDATE urls SET url = ?, updatedAt = ? WHERE shortCode = ?",
                (new_url, now, short_code))
    conn.commit()
    updated = cur.rowcount
    conn.close()

    if updated:
        return {"message": "URL updated successfully"}
    else:
        return {"error": "Short code not found"}

# 🔸 Test it:
update_url("abc123", "https://updated-url.com")


def delete_url(short_code):
    conn = sqlite3.connect("database.db")
    cur = conn.cursor()
    cur.execute("DELETE FROM urls WHERE shortCode = ?", (short_code,))
    conn.commit()
    deleted = cur.rowcount
    conn.close()

    if deleted:
        return {"message": "URL deleted successfully"}
    else:
        return {"error": "Short code not found"}

# 🔸 Test it:
delete_url("abc123")

def get_url_stats(short_code):
    conn = sqlite3.connect("database.db")
    cur = conn.cursor()
    cur.execute("SELECT * FROM urls WHERE shortCode = ?", (short_code,))
    row = cur.fetchone()
    conn.close()

    if row:
        return {
            "id": row[0],
            "url": row[1],
            "shortCode": row[2],
            "createdAt": row[3],
            "updatedAt": row[4],
            "accessCount": row[5]
        }
    else:
        return {"error": "Short code not found"}

# 🔸 Test it:
get_url_stats("abc123")

